package main

import "fmt"

func printInstructions() {
  fmt.Println("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:")
  fmt.Println("1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...")
  fmt.Println("By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.")
}

func printAnswer(ans int) {
  fmt.Println("The answer is:", ans)
}

func sumMultiples(stopAt int) int{
  return 5
}

func main() {
  printInstructions()
  ans := sumMultiples(1000)
  printAnswer(ans)
}
